// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hero": {
    "title": "All-in-One Video Enhancements",
    "subtitle": "30+ features in one, the ultimate video experience enhancement browser extension with multi-platform support, helping you easily master your video experience.",
    "chrome": "Chrome",
    "edge": "Edge",
    "firefox": "Firefox",
    "featuresTitle": "Everything You Need for Video",
    "advantagesTitle": "Why Choose Us?",
    "reviewsTitle": "User Reviews",
    "interfaceTitle": "Friendly User Interface",
    "rating": "5.0",
    "usersTrust": "Trusted by 20,000+ users around the world",    "animation": {
      "prefix": "Your exclusive Video",
      "0": { "text": "Rotator." },
      "1": { "text": "Downloader." },
      "2": { "text": "Recorder." },
      "3": { "text": "AI Summarizer." },
      "4": { "text": "VR Glasses." },
      "5": { "text": "Pitch Shifter." },
      "6": { "text": "Audio Delayer." },
      "7": { "text": "Looper." },
      "8": { "text": "Zoomer." },
      "9": { "text": "Player." },
      "10": { "text": "Filter." },
      "11": { "text": "Speeder." },
      "12": { "text": "Ad Accelerator." }
    },    "features": [
      {
        "title": "Absolute Privacy Protection",
        "desc": "The extension does not collect any user information and we use Chrome's built-in API to ensure user privacy and security."
      },
      {
        "title": "Extensive Platform Support",
        "desc": "Supports all websites and platforms using HTML5 video, enjoy enhanced experience anytime, anywhere."
      },
      {
        "title": "30+ Features",
        "desc": "30+ features in one, no need to download multiple extensions, one extension handles all your needs. Not just rotation, zoom, picture-in-picture, stretch, loop, speed control, VR, screenshot, filters, download... but also volume enhancement, audio delay, pitch adjustment, 3D surround effects, and more."
      },
      {
        "title": "Built-in Independent Web Player",
        "desc": "For features not supported by local players, you can directly upload video files to Video Roll for playback and enjoy all Video Roll features."
      },
      {
        "title": "Customizable Shortcuts",
        "desc": "Support custom shortcuts, operate more efficiently and conveniently without opening the extension."
      },
      {
        "title": "YouTube Feature Enhancement",
        "desc": "For YouTube, provides automatic ad detection and accelerated playback (not ad blocking), and video AI summarization. Making your YouTube experience richer."
      },
      {
        "title": "Multi-window Sync",
        "desc": "Sync playback progress across multiple windows, switch more freely."
      },
      {
        "title": "Volume Enhancement",
        "desc": "Increase volume limit, hear more clearly."
      },
      {
        "title": "Subtitle Translation",
        "desc": "One-click subtitle translation, barrier-free across languages."
      }
    ],
    "advantages": [
      {
        "title": "More Features",
        "desc": "Support more platforms and features"
      },
      { "title": "Better Experience", "desc": "Clean UI, smooth operation" },
      { "title": "Open Source", "desc": "Open source code, safe and reliable" }
    ],
    "reviews": [
      { "user": "Xiaoming", "comment": "Five stars! Super convenient!" },
      { "user": "Alice", "comment": "Ad skip is awesome, great experience." },
      {
        "user": "Bob",
        "comment": "Multi-platform support, highly recommended."
      },
      { "user": "Zhang San", "comment": "Rich features, easy to use." },
      { "user": "Li Si", "comment": "Beautiful UI, five stars!" }
    ]
  },
  "dashboard": {
    "navigation": {
      "profile": "Profile",
      "privacy": "Data & Privacy",
      "subscription": "Subscription",
      "about": "About"
    },
    "profile": {
      "googleAccount": "Google Account",
      "githubAccount": "GitHub Account",
      "emailAccount": "Email Account",
      "accountInfo": "Account Information",
      "loginEmail": "Login Email",
      "loginMethod": "Login Method",
      "googleOAuth": "Google OAuth",
      "githubOAuth": "GitHub OAuth",
      "emailPassword": "Email & Password"
    },
    "privacy": {
      "title": "Data and Privacy Statement",
      "intro": "We take your data security and privacy protection very seriously. This plugin promises:",
      "policies": {
        "0": "Your personal information is only used for account login and basic service functions",
        "1": "We will not use your data for any commercial promotion purposes",
        "2": "Your data will not be leaked or sold to any third parties",
        "3": "All data transmission is encrypted",
        "4": "You can delete your account and related data at any time"
      },
      "footer": "For more details, please check our complete privacy policy. If you have any questions, please contact us at any time."
    },
    "subscription": {
      "title": "Subscription Information",
      "freePlan": "Free Plan",
      "freePlanDesc": "You are using the free plan and enjoying all basic features",
      "features": {
        "0": "Basic video download features",
        "1": "Multi-format support",
        "2": "Basic technical support"
      },
      "upgrade": "Upgrade Plan (Coming Soon)"
    },
    "about": {
      "title": "About VideoRoll Pro",
      "description": "VideoRoll Pro is a powerful video download browser extension that supports multiple video formats and websites.",
      "pluginInfo": "Plugin Information",
      "version": "Version:",
      "developer": "Developer:",
      "contact": "Contact Information",
      "email": "Email:",
      "website": "Website:"
    }
  },
  "pricing": {
    "title": "Choose Your Plan",
    "subtitle": "VideoRoll offers flexible plan options to meet different user needs",
    "free": {
      "title": "Free Plan",
      "price": "Free",
      "description": "✨ No login or payment required, use for free immediately",
      "button": "Get Started"
    },
    "pro": {
      "title": "Pro Plan",
      "price": "Free",
      "priceNote": "(Limited Time)",
      "description": "🎉 This plan is currently open for free registration",
      "disclaimer": "* May be adjusted to paid features in the future",
      "button": "Register for Pro",
      "recommended": "Recommended"
    },
    "features": {
      "video": {
        "title": "Video Features",
        "rotate": "Video Rotation",
        "download": "Video Download",
        "video_url": "Video Stream Copy",
        "video_url_qr": "Video Stream QR Code",
        "loop": "Video Loop",
        "zoom": "Video Zoom",
        "rotate_adaptive": "Rotation Adaptive Container",
        "reposition": "Video Position Movement",
        "focus": "Focus Mode",
        "player": "Built-in Player",
        "filter": "Video Filters",
        "speed": "Playback Speed Control",
        "pip": "Picture-in-Picture",
        "web_qr": "Web QR Code",
        "screenshot": "Video Screenshot",
        "video_stretch": "Video Stretch",
        "advanced_pip": "Video Window Separation",
        "ai_summary": "YouTube AI Video Summary",
        "record": "Video Recording",
        "ab_loop": "A-B Loop",
        "vr": "VR Mode"
      },
      "audio": {
        "title": "Audio Features",
        "volume_boost": "Volume Boost",
        "pitch": "Pitch Adjustment",
        "audio_delay": "Audio Delay",
        "audio_stereo": "Audio Stereo",
        "3d_surround": "3D Surround Sound"
      },
      "other": {
        "title": "Other Features",
        "ad_accelerator": "YouTube Ad Accelerator",
        "platform_support": "Multi-Platform Support",
        "disable": "One-Click Disable",
        "cache_list": "Cache Websites",
        "disable_list": "Disable Websites",
        "custom_shortcuts": "Custom Shortcuts",
        "custom_layout": "Custom Interface Layout"
      }
    },
    "whyChoose": {
      "title": "Why Choose VideoRoll?",
      "feature1": "Completely free core features",
      "feature2": "No mandatory registration",
      "feature3": "Privacy and security protection"
    }
  },
  "footer": {
    "links": {
      "privacy": "Privacy Policy",
      "about": "About Us",
      "contact": "Contact Us",
      "friendlyLinks": "Friendly Links",
      "bugReport": "Bug Report"
    },
    "copyright": "All rights reserved"
  },
  "nav": {
    "features": "Features",
    "pricing": "Pricing",
    "faq": "FAQ",
    "documentation": "Documentation",
    "language": "Language"
  },
  "welcome": {
    "congratulations": "Congratulations on successfully installing",
    "appName": "Video Roll",
    "subtitle": "Start your video enhancement journey~",
    "exploreButton": "Explore More on Official Website →"
  },
  "auth": {
    "signinTitle": "Sign in to Video Roll",
    "signupTitle": "Sign up for Video Roll",
    "email": "Email",
    "password": "Password",
    "enterEmail": "Enter your email",
    "enterPassword": "Enter your password",
    "emailInvalid": "Please enter a valid email",
    "signin": "Sign in",
    "signup": "Sign up",
    "signinWithGoogle": "Sign in with Google",
    "signinWithGithub": "Sign in with Github",
    "signupWithGoogle": "Sign up with Google",
    "signupWithGithub": "Sign up with Github",
    "noAccount": "Don't have an account?",
    "hasAccount": "Already have an account?",
    "signupLink": "Sign up",
    "signinLink": "Sign in",
    "captchaError": "Can't verify captcha",
    "captchaErrorDesc": "Please try again later.",
    "error": "Error",
    "oauthError": "Login credentials or grant type not recognized",
    "oauthFailed": "OAuth authentication failed",
    "unexpectedError": "An unexpected error occurred",
    "agreementText": "By registering/signing in, you agree to our",
    "termsOfService": "Terms of Service",
    "and": "and",
    "privacyPolicy": "Privacy Policy"
  }
};
export default messages;